### ISSUE TITLE
NewPipe_preunified v0.21.1-legacy - Crash at start

### ISSUE THREAD

**Issue by ZacharyFoxx** [XiangRongLin/NewPipe-preuinified#1]
First of all, thank you for your support.

I tried, but the app crashed as soon as it started.

Screenshots with the error report
![screen-01](https://user-images.githubusercontent.com/23250218/114326335-a7ac5780-9b0a-11eb-9959-c7e4eb000c1e.png)
![screen-02](https://user-images.githubusercontent.com/23250218/114326337-aaa74800-9b0a-11eb-9d13-1ffa83a95a98.png)

 attached (Sorry, I didn't can save it on a txt file).

**Comment by ShareASmile** [comment]
See
https://github.com/TeamNewPipe/NewPipe-legacy/issues/38

**Comment by XiangRongLin** [comment]
I'll try to fix this on Thursday/weekend. I missed all issues since i didn't have notifications on and usually don't look here

**Comment by ZacharyFoxx** [comment]
> I'll try to fix this on Thursday/weekend. I missed all issues since i didn't have notifications on and usually don't look here

Hi,

Just to clarify, I know that your job in maintaining this fork is voluntary and in no way my issue here or the comment in the other issue is to demand anything from you.

A suggestion is to look at the fix that was applied to the user blackbox87 on his fork, in this issue of NewPipe Legacy: https://github.com/TeamNewPipe/NewPipe-legacy/issues/38

Finally, I would like to thank you for maintaining this fork.

Thank you very much.

**Comment by XiangRongLin** [comment]
Can you try out this. Im surprised, that the emulator does not crash like that, even before i made these changes https://github.com/XiangRongLin/NewPipe-preuinified/commit/9d43a717c72750376c79634de6c8ef218d37219c

[app-release.zip](https://github.com/XiangRongLin/NewPipe-preuinified/files/6359906/app-release.zip)

**Comment by ZacharyFoxx** [comment]
> Can you try out this. Im surprised, that the emulator does not crash like that, even before i made these changes [9d43a71](https://github.com/XiangRongLin/NewPipe-preuinified/commit/9d43a717c72750376c79634de6c8ef218d37219c)
> 
> [app-release.zip](https://github.com/XiangRongLin/NewPipe-preuinified/files/6359906/app-release.zip)

Yes I will try.

**Comment by ZacharyFoxx** [comment]
@XiangRongLin tested and it's working :+1: !
