### ISSUE TITLE
new dislikes being treated as errors

### ISSUE THREAD

**Issue by kubo6472** [XiangRongLin/NewPipe-preuinified#12]
Youtube removed access to public dislikes a month ago. Every video since errors out on dislikes. Is there an approx of active users of this? Or am I the only one still standing and resisting the unification. I tried the latest app just to check, and it's bad, it's annoying, so I hope that this fork continues to exist.

**Comment by XiangRongLin** [comment]
Should be fixed by https://github.com/TeamNewPipe/NewPipeExtractor/pull/753, which will be integrated here when it is released

**Comment by XiangRongLin** [comment]
> Is there an approx of active users of this?

Look at the api for the releases. Here under assets you can see the download count of the latest release which is only 219
https://api.github.com/repos/XiangRongLin/NewPipe-preuinified/releases

---

On a side note they rolled it out gradually, so some peoply may not experience these issues yet

**Comment by XiangRongLin** [comment]
released
