### ISSUE TITLE
Maintain this project and rename it to OldPipe

### ISSUE THREAD

**Issue by rikishi0071** [XiangRongLin/NewPipe-preuinified#13]
#### Describe the feature you want
Maintain this project and release new versions when new versions of NewPipe Extractor releases.

#### Is your feature request related to a problem? Please describe it
No

#### Additional context
It seems like NewPipe developers won't return back the old interface. I think old interface is great.

#### How will you/everyone benefit from this feature?
People who want to have NewPipe with old user interface will get new versions released.

**Comment by XiangRongLin** [comment]
> Maintain this project and release new versions when new versions of NewPipe Extractor releases.

It already is. The latest Extractor release is 0.21.11, which is used here

> rename it to OldPipe

Feel free to fork it yourself. I'm leaving the name as is (even with the typo), because this will not be a long term thing from me.
