### ISSUE TITLE
No more NewPipe Legacy?

### ISSUE THREAD

**Issue by xn117khdsh** [XiangRongLin/NewPipe-preuinified#14]
Hi. I am a huge fan of NewPipe because I can watch YouTube videos without ads. However, I only use the Legacy version of NewPipe as I have used it for a long time and I like the older UI. So I have a question: Is that true that you don't make newer Legacy versions anymore?
I'm sorry if my English has some problems as it isn't my native language.

**Comment by XiangRongLin** [comment]
To be honest, I didn't think anyone was still using it, so I stopped bothering. 
Since that does not seem to be the case I added the setup to automatically release it too and let it run yesterday.

**Comment by xn117khdsh** [comment]
Thank you so much for releasing the latest version of NewPipe Legacy. For some reasons, I don't like using the newer version, so I decided to keep using the Legacy version. I'm still using the 0.21.8-legacy which was made by you as Team NewPipe don't make that version anymore.

**Comment by DI555** [comment]
@XiangRongLin ,thank you, good man!
i use your both two preunified versions either, please, keep its updated!
and even more, i use yours nightly versions too!!!
keep its all rolling, please !!!
