### ISSUE TITLE
"View on GitHub" link to this fork

### ISSUE THREAD

**Issue by SpazMahTazz** [XiangRongLin/NewPipe-preuinified#17]
#### Describe the feature you want

If possible, and if you think it's a good idea, can we please make the link in the side tab > About > Contribute > View on GitHub link to this fork rather than the original fork?

#### How will you/everyone benefit from this feature?

If the link was updated, we could use it to do things like go to the new releases directly from NewPipe Pre-unified itself.

**Comment by XiangRongLin** [comment]
https://github.com/XiangRongLin/NewPipe-preuinified/blob/pre-unified/app/src/main/java/org/schabi/newpipe/about/AboutActivity.java#L144

**Comment by kubo6472** [comment]
Since nobody seemed to care and to lift off the 0.21.14 release off the ground I made this little edit to help tidy up the issues a bit.
