### ISSUE TITLE
can we build on a specific extractor commit? 

### ISSUE THREAD

**Issue by kubo6472** [XiangRongLin/NewPipe-preuinified#24]
Extractor broke, no release yet, upstream apk based on this commit was published for now, doesn't help here: https://github.com/TeamNewPipe/NewPipeExtractor/commit/bebdc55ad42ef964a547059110573a177331cf4d

**Comment by XiangRongLin** [comment]
Yes we can 🇺🇸 
https://github.com/XiangRongLin/NewPipe-preuinified/commit/0d5c31ba767dfea03d3d6ab370038d9bc25ad332
https://github.com/XiangRongLin/NewPipe-preuinified/commit/49011c8325ea4c186e133e57722f0838143d5078

Release is running/should be out

**Comment by kubo6472** [comment]
Confirmed works, thanks
