### ISSUE TITLE
Is this project no longer supported?

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [XiangRongLin/NewPipe-preuinified#5]
NewPipe-preuinified has been using extractor 0.21.3 since May, while https://github.com/TeamNewPipe/NewPipeExtractor is already at 0.21.6.

**Comment by XiangRongLin** [comment]
I haven't found the time to do it. And since nothing of note was changed i did not create a new release. Is there something that you need from the new versions?

**Comment by nbmrjuhneibkr** [comment]
I see some fixes for age-restricted videos in 0.21.6 changelog. I didn't watch such videos recently, but this might be something important.

Either way - glad to see that it hasn't been abandoned.

**Comment by XiangRongLin** [comment]
new release was made
